### ISSUE TITLE
[Question] config.yml

### ISSUE THREAD

**Issue by revisorydooryt** [Jumper251/AdvancedReplay#217]
what does each line do? i need to understand them all, comments are missing

```
general:
  max_length: 86400
  record_on_startup: true
  save_on_stop: true
  use_mysql: false
  use_s3: false
  use_offline_skins: false+
  quality: high
  cleanup_replays: -1
  hide_players: false
  add_new_players: true
  update_notifications: true
replaying:
  world:
    reset_changes: false
  progress_display: action_bar
recording:
  blocks:
    enabled: true
    real_changes: true
  entities:
    enabled: true
    items:
      enabled: true
  chat:
    enabled: true
    format: '&r<{name}> {message}'
```
