### ISSUE TITLE
Replays Randomly freeze after about a minute

### ISSUE THREAD

**Issue by TrixxTraxx** [Jumper251/AdvancedReplay#49]
So I am having this issue that after about 60s depending on the replay the replay just freezes, I dont get any error message neither when recording nor when replaying, I am recording between 6 and 8 players at a time, I store it in mysql and my config looks like this:

```
general:
  max_length: 3600
  record_on_startup: false
  save_on_stop: false
  use_mysql: true
  use_offline_skins: true
  quality: high
  cleanup_replays: -1
  hide_players: false
  add_new_players: true
  update_notifications: true
  death_message: '&6{name} &7died.'
  quit_message: '&6{name} &7left the game.'
  join_message: '&6{name} &7joined the game.'
replaying:
  world:
    reset_changes: false
recording:
  blocks:
    enabled: true
    real_changes: true
  entities:
    enabled: true
    items:
      enabled: true
  chat:
    enabled: false
    format: '&r<{name}> {message}'
```
    
    Example Replay:
    id: Bedwars-14
    creator: CONSOLE
    duraction: 14995
    time: 1633896354757
    bin: https://www.mediafire.com/file/4znn4kw3dt9qbxz/replays-data_%25281%2529.bin/file
    
I replay it on a different server by loading the map and then starting the replay with a plugin I made myself

relevant plugins:

Slime world manager
Bedwars1058
Proctolib
Skin Restorer
idk dont think any others could have any effects, if anything most likely Slime world manager

Quickest responce will be over Discord: TrixxTraxx#8555
