### ISSUE TITLE
Replays don't save when /stop command used

### ISSUE THREAD

**Issue by SpicySoap** [Jumper251/AdvancedReplay#52]
My server automatically starts recording when it starts, and should save when it is stopped (happens routinely throughout the day). This isn't working, and I'm left with replays claiming to be 0 seconds long, and not doing anything.

**Comment by Jumper251** [comment]
Can you send me your config.yml

**Comment by SpicySoap** [comment]
Copy attached below
```
general:
  max_length: 86400
  record_on_startup: true
  save_on_stop: true
  use_mysql: false
  use_offline_skins: true
  quality: low
  cleanup_replays: -1
  hide_players: false
  add_new_players: true
  update_notifications: true
  death_message: '&6{name} &7died.'
  quit_message: '&6{name} &7left the game.'
  join_message: '&6{name} &7joined the game.'
replaying:
  world:
    reset_changes: true
recording:
  blocks:
    enabled: true
    real_changes: true
  entities:
    enabled: true
    items:
      enabled: true
  chat:
    enabled: true
    format: '&r<{name}> {message}'

```
